code --install-extension 4ops.terraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.makefile-tools
code --install-extension redhat.vscode-yaml
code --install-extension vscodevim.vim
code --install-extension golang.go 
code --install-extension maxnatchanon.go-struct-tag-autogen
code --install-extension premparihar.gotestexplorer 
code --install-extension eamodio.gitlens
code --install-extension reduckted.vscode-gitweblinks
code --install-extension eriklynd.json-tools
code --install-extension rubymaniac.vscode-direnv
code --install-extension dzhavat.bracket-pair-toggler
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension tomoki1207.pdf
code --install-extension valentjn.vscode-ltex
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension usernamehw.errorlens
code --install-extension miguelsolorio.min-theme
code --install-extension miguelsolorio.symbols
code --install-extension oderwat.indent-rainbow
code --install-extension naumovs.color-highlight
