code --install-extension 4ops.terraform
code --install-extension angular.ng-template
code --install-extension docker.docker
code --install-extension dzhavat.bracket-pair-toggler
code --install-extension eamodio.gitlens
code --install-extension eriklynd.json-tools
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension janisdd.vscode-edit-csv
code --install-extension maxnatchanon.go-struct-tag-autogen
code --install-extension miguelsolorio.min-theme
code --install-extension miguelsolorio.symbols
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.makefile-tools
code --install-extension oderwat.indent-rainbow
code --install-extension premparihar.gotestexplorer
code --install-extension redhat.vscode-yaml
code --install-extension reduckted.vscode-gitweblinks
code --install-extension rubymaniac.vscode-direnv
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension stevejpurves.cucumber
code --install-extension tomoki1207.pdf
code --install-extension usernamehw.errorlens
code --install-extension valentjn.vscode-ltex
